import React from 'react';
import ReactDOM from 'react-dom/client';
import { App } from './App';
import { parsePath } from './utils/routes';
import './index.css';
const location = parsePath(window.location.pathname);
const root = document.getElementById('root')!;
const app = <React.StrictMode><App initialRoute={location.route} initialLang={location.lang} /></React.StrictMode>;
if (root.hasChildNodes()) ReactDOM.hydrateRoot(root, app);
else ReactDOM.createRoot(root).render(app);
